# Generated by Django 2.1.1 on 2018-10-09 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='tags',
        ),
    ]
