# Generated by Django 2.1.1 on 2018-10-09 10:00

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_remove_module_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='structure.TaggedItem', to='structure.StudetlyTag', verbose_name='Tags'),
        ),
    ]
